### PR TITLE
resource-links.md: add Social of AE with Extn

### PR DESCRIPTION
**Pull request by Danielcalza**
Adding resources and links from Issue #1 to the websites' further readings page.

### CODE REVIEW

**Comment by Danielcalza** [comment]
I'm not sure if I should close this one since I created another one for the second adding of resources, and it seems to also include this commit?

**Comment by Danielcalza** [comment]
I think now see that each commit if dealing with a different section or file, should be on a different branch to be able to separate the pull requests correct? 


The last two commits are from #2 and #3

**Comment by brymz** [comment]
Yes. To avoid merge conflicts different activities should be on different branches. You may group changes for different sections or files, but your grouping should be deliberate. Now that the changes are live, review the website to make sure everything works.

**Comment by Danielcalza** [comment]
Okay I understand now, and will keep this in mind for best practices. I reviewed the site and fixed link, all looks good and works.

**Pull request merged**
